github_instances:
  - instance: COM
    url: https://github-instance-1.example.com
    organizations:
      - name: org1
        owners:
          - cvega
          - owner2
  - instance: EMU
    url: https://github-instance-2.example.com
    organizations:
      - name: org2
        owners:
          - owner3
  - instance: SOMA
    url: https://github-instance-3.example.com
    organizations:
      - name: org3
        owners:
          - owner4
          - owner5
          - owner6
