github_instances:
  - instance: COM
    url: github.com
    organizations:
      - name: sdfc-demo
        owners:
          - cvega
          - owner2
  - instance: EMU
    url: pluehne-1682694429.gh-quality.net
    organizations:
      - name: org2
        owners:
          - owner3
  - instance: SOMA
    url: https://github-instance-3.example.com
    organizations:
      - name: org3
        owners:
          - owner4
          - owner5
          - owner6
