github_instances:
  - instance: github_instance_1
    url: https://github-instance-1.example.com
    organizations:
      - name: org1
        owners:
          - cvega
          - owner2
  - instance: github_instance_2
    url: https://github-instance-2.example.com
    organizations:
      - name: org2
        owners:
          - owner3
  - instance: github_instance_3
    url: https://github-instance-3.example.com
    organizations:
      - name: org3
        owners:
          - owner4
          - owner5
          - owner6
