name: create an organization webhook
description: Organization webhooks allow you to receive HTTP POST payloads whenever certain events happen in a organization.
title: "[req] create an organization webhook"
labels: ["organization", "web hook"]
body:
  - type: dropdown
    id: instance
    attributes:
      label: GitHub Instance
      description: The instance of Github you're targeting. 
      options:
        - github.com
        - github.com EMU
        - github enterprise (SOMA)
  - type: input
    id: organization
    attributes:
      label: GitHub Organization
      description: The name of the github organization (must be exact)
      placeholder: ex. salesforce
  - type: input
    id: url
    attributes:
      label: Payload URL
      description: The webhook url
      placeholder: https://example.com/post
  - type: dropdown
    id: content_type
    attributes:
      label: Content type
      description: 
      options:
        - application/json
        - application/x-www-form-urlencoded
  - type: checkboxes
    id: secret
    attributes:
      label: Secret
      description: This will generate a secret that will be emailed to the user (e.g. github.actor)
      options:
        - label: Enable secret (not required)
   - type: markdown
      attributes:
        value: |
          ***
