name: create an organization webhook
description: Organization webhooks allow you to receive HTTP POST payloads whenever certain events happen in a organization.
title: "[req] create an organization webhook"
labels: ["organization", "web hook"]
assignees:
  - octocat
body:
  - type: dropdown
    id: instance
    attributes:
      label: GitHub Instance
      description: What instance of GitHub are you targetting?
      options:
        - github.com
        - github.com EMU
        - github enterprise (SOMA)
  - type: input
    id: organization
    attributes:
      label: GitHub Organization
      description: The name of the github organization
      placeholder: ex. salesforce
  - type: input
    id: url
    attributes:
      label: Payload URL
      description: Enter the web hook url
      placeholder: https://example.com/post
