name: issue ops

on:
  issues:
    types:
      - opened


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/org-webhook.yml

      - run: cat ${HOME}/issue-parser-result.json

      - run: echo $INSTANCE
        env:
          FAVORITE_DISH: ${{ steps.issue-parser.outputs.issueparser_instance }}

