name: issue-ops / self-service

on:
  issues:
    types:
      - opened


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/org-webhook.yml

      - run: |
          python .github/scripts/validate_role.py \
            --github_instance=$INSTANCE \
            --organization=$ORGANIZATION
            --user=${{ github.actor }}

