name: issue-ops / self-service

on:
  issues:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: parse issue
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/org-webhook.yml
          
      - run: cat ${HOME}/issue-parser-result.json

      - name: validate required keys
        env:
          INSTANCE: ${{ steps.issue-parser.outputs.issueparser_instance }}
          ORGANIZATION: ${{ steps.issue-parser.outputs.issueparser_organization }}
        run: |
          python .github/scripts/validate_required-keys.py \
            --required_keys_file=.github/ISSUE_TEMPLATE_REQUIRED_KEYS/org-webhook.yml \
            --json_file=${HOME}/issue-parser-result.json

      - name: validate role
        env:
          INSTANCE: ${{ steps.issue-parser.outputs.issueparser_instance }}
          ORGANIZATION: ${{ steps.issue-parser.outputs.issueparser_organization }}
        run: |
          python .github/scripts/validate_role.py \
            --github_instance=$INSTANCE \
            --organization=$ORGANIZATION \
            --user=${{ github.actor }}

