name: issue-ops / self-service

on:
  issues:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: parse issue
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/org-webhook.yml

      - name: validate required form entries
        run: |
          # Run the script and capture the output
          validation_output=$(python .github/scripts/validate_required_keys.py \
            --required_keys_file=.github/ISSUE_TEMPLATE_REQUIRED_KEYS/org-webhook.yml \
            --json_file=${HOME}/issue-parser-result.json)
          # Set the environment variable for subsequent steps
          echo "VALIDATION_OUTPUT=$validation_output" >> $GITHUB_ENV

      - name: update issue with validation failure message
        if: ${{ failure() }} 
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            // Use the environment variable in the script
            const failureMessage = process.env.VALIDATION_OUTPUT || 'Validation failed. Please check your inputs and try again.';
            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: failureMessage,
            });

      - name: validate role
        env:
          INSTANCE: ${{ steps.issue-parser.outputs.issueparser_instance }}
          ORGANIZATION: ${{ steps.issue-parser.outputs.issueparser_organization }}
        run: |
          python .github/scripts/validate_role.py \
            --github_instance=$INSTANCE \
            --organization=$ORGANIZATION \
            --user=${{ github.actor }}

